service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs8.10
  stage: dev

functions:
  users:
    handler: handler.users
    events:
      - http:
          method: get
          path: users
